FROM alpine:3.14
# Create app directory
WORKDIR /usr/src/app
# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN apk update 
RUN apk add texlive
RUN apk add texmf-dist-latexextra
RUN apk add npm
RUN npm install
RUN npm add amqplib
RUN npm install uuid
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .
#COPY ./boot.sh /sbin/boot.sh
#COPY ./latex.init /etc/service/latex/run
#COPY ./latex-service.js /root/latex-service.js